### ISSUE TITLE
Investigate What PWA is ?

### ISSUE THREAD

**Issue by knowprabhjyot** [PhucMaii/RestaurantApp#54]
What is a PWA ?
What is a service Worker ?
What are the benefits of PWA ?
What are push Notifications ?
How we can run app in offline Mode ?

**Comment by PhucMaii** [comment]
1. PWA stands for Progressive Web Apps which converts a web created from HTML, CSS, Javascript into an app. I offers an enhanced user experience similar to native apps. It can be accessed through various device like phone, tablets, and also desktop computers. 
2. Service Worker s a type of Javascript script which runs behind the scene of a web application. It acts like a proxy between a web app and network which is essential for PWA. Service worker provides some features such as offline support, push notification, etc. It perform tasks in the background like intercepting network and caching resources to provide a more app-like experience. 
3. Benefits of PWA
   1. Responsive Design and Progressive Enhancement: PWA are typically responsive, adapting different screen sizes so it is suitable for all devices. PWA are built with progressive enhancement approach. Therefore, it provides good performance on all different device or network.  
   2. Offline Supports: thanks to service worker which intercepts and cache resources, PWA can work offline or in low-network environment. 
   3. Fast Loading
   4. Push Notifications: PWAs can send notification s to user's device even though users are not active
   5. Security: PWAs served through HTTPS to ensure data privacy
   6. Automatic Update
   7. Cross-Platforms
4. Push Notifications are messages or alerts sent to user devices even though users are not active on the app. It usually pops up n the notification center of a device. It provide real-time update feature and offline support as well
5. Service Worker is the key technology to un offline mode. It intercepts networks and respond with cached contents in offline mode
